name: dr1bclone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  dismissible_page: ^1.0.1
  fl_chart: ^0.60.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_gif: ^0.0.4
  flutter_staggered_animations: ^1.1.1
  get: 4.6.5
  glassmorphism: ^3.0.0
  google_fonts: ^4.0.3
  lottie: ^2.2.0
  pie_chart: ^5.3.2
  scroll_to_index: ^3.0.1
  translator: ^0.1.7
  url_launcher: ^6.1.9
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/foto/
    - assets/icon/
    - assets/portofolio/
    - assets/logo/
    - assets/sertif/
    - assets/button/
